version: '3.9'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/Dockerfile
  #   volumes:
  #     - .:/workspace:cached
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis

  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_DB: vionix
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  pgdata:
  #redisdata:
  minio-data: