"""add auto_download column in youtube_channel_source

Revision ID: 0abb01e7e791
Revises: a360d7b1032d
Create Date: 2025-05-06 21:40:03.504880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abb01e7e791'
down_revision: Union[str, None] = 'a360d7b1032d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channel_sources', sa.Column('auto_download', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channel_sources', 'auto_download')
    # ### end Alembic commands ###
