"""add video and audio path

Revision ID: 4557a3593c01
Revises: c8e991a8b18c
Create Date: 2025-04-21 23:31:09.694003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4557a3593c01'
down_revision: Union[str, None] = 'c8e991a8b18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_path', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('audio_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'audio_path')
    op.drop_column('videos', 'video_path')
    # ### end Alembic commands ###
