"""add thumbnail_path

Revision ID: 7e747d20738a
Revises: c2ed84cce646
Create Date: 2025-05-06 14:20:29.416144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e747d20738a'
down_revision: Union[str, None] = 'c2ed84cce646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channel_sources', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_channel_sources', 'thumbnail_path')
    # ### end Alembic commands ###
