"""add text to chunk table

Revision ID: 9245a483f5e3
Revises: cef6bdb1c2c7
Create Date: 2025-04-26 14:10:13.912671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9245a483f5e3'
down_revision: Union[str, None] = 'cef6bdb1c2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text', sa.String(), nullable=False))
    op.alter_column('chunks', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_column('chunks', 'text')
    # ### end Alembic commands ###
