"""change to multiple source types

Revision ID: a0369b080a50
Revises: b010011e432f
Create Date: 2025-04-21 20:43:44.332824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0369b080a50'
down_revision: Union[str, None] = 'b010011e432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_upload_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_channel_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_playlist_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('sources', 'external_id')
    op.drop_column('sources', 'name')
    op.add_column('video_stats', sa.Column('other_metrics', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'updated_at')
    op.drop_column('video_stats', 'other_metrics')
    op.add_column('sources', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('youtube_playlist_sources')
    op.drop_table('youtube_channel_sources')
    op.drop_table('manual_upload_sources')
    # ### end Alembic commands ###
