"""add thumbnail_path

Revision ID: c2ed84cce646
Revises: 778bdcb9b4cc
Create Date: 2025-05-06 09:49:34.355696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ed84cce646'
down_revision: Union[str, None] = '778bdcb9b4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail_path', sa.String(), nullable=True))
    op.add_column('youtube_playlist_sources', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_playlist_sources', 'thumbnail_path')
    op.drop_column('videos', 'thumbnail_path')
    # ### end Alembic commands ###
