"""add some properties

Revision ID: c8e991a8b18c
Revises: a0369b080a50
Create Date: 2025-04-21 23:20:25.517128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8e991a8b18c'
down_revision: Union[str, None] = 'a0369b080a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_stats', 'comments')
    op.drop_column('video_stats', 'likes')
    op.drop_column('video_stats', 'other_metrics')
    op.add_column('videos', sa.Column('author', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=False))
    op.add_column('videos', sa.Column('published_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('videos', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('videos', 'updated_at')
    op.add_column('youtube_channel_sources', sa.Column('name', sa.String(), nullable=False))
    op.add_column('youtube_channel_sources', sa.Column('url', sa.String(), nullable=False))
    op.add_column('youtube_channel_sources', sa.Column('thumbnail_url', sa.String(), nullable=False))
    op.add_column('youtube_playlist_sources', sa.Column('title', sa.String(), nullable=False))
    op.add_column('youtube_playlist_sources', sa.Column('owner', sa.String(), nullable=False))
    op.add_column('youtube_playlist_sources', sa.Column('thumbnail_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_playlist_sources', 'thumbnail_url')
    op.drop_column('youtube_playlist_sources', 'owner')
    op.drop_column('youtube_playlist_sources', 'title')
    op.drop_column('youtube_channel_sources', 'thumbnail_url')
    op.drop_column('youtube_channel_sources', 'url')
    op.drop_column('youtube_channel_sources', 'name')
    op.add_column('videos', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('videos', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('videos', 'published_at')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'length')
    op.drop_column('videos', 'author')
    op.add_column('video_stats', sa.Column('other_metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('video_stats', sa.Column('likes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('video_stats', sa.Column('comments', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
