"""add worker_logs

Revision ID: e0adc41d492b
Revises: 7e747d20738a
Create Date: 2025-05-06 16:58:43.321586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0adc41d492b'
down_revision: Union[str, None] = '7e747d20738a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='log_level_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('func_name', sa.String(length=255), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.Column('pathname', sa.String(length=1024), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_logs_created_at'), 'worker_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_worker_logs_level'), 'worker_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_logs_level'), table_name='worker_logs')
    op.drop_index(op.f('ix_worker_logs_created_at'), table_name='worker_logs')
    op.drop_table('worker_logs')
    # ### end Alembic commands ###
