"""renove upload_date from video

Revision ID: e0bde364f332
Revises: c0ff2133b3a6
Create Date: 2025-04-25 16:27:45.454256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0bde364f332'
down_revision: Union[str, None] = 'c0ff2133b3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('language', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('transcription', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'transcription')
    op.drop_column('videos', 'language')
    # ### end Alembic commands ###
